"""
Django settings for mi_blog project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv # Asegúrate de tener esto para cargar el .env

load_dotenv() # Carga las variables del archivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=m%%xkwr8yvie104^07yr)gs)ku_=b5alx6teqqibi7j2s9s*o'

# SECURITY WARNING: don't run with debug turned on in production!
# mi_blog_profesional/settings.py

DEBUG = True # <--- ¡IMPORTANTE! Las páginas de error personalizadas solo se muestran con DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] # <--- ¡También debes configurar esto cuando DEBUG = False!
                                         # Agrega el dominio de tu sitio web si lo tienes desplegado


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Tiene que estar antes de 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Mis aplicaciones
    'usuarios',
    'blog',
    'home',
    # Aplicaciones de terceros
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mi_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'NAME_DB',
      # 'NAME': os.environ.get('NAME_DB', 'NOMBREGITHUB$NAME_DB'), 
        'USER': 'USER_DB', 
        'PASSWORD': 'PASSWORD_DB',
      # 'HOST': 'NOMBREGITHUB.mysql.pythonanywhere-services.com',
        'PORT': "3306",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ar' # Español de Argentina

TIME_ZONE = 'America/Argentina/Buenos_Aires' # Zona horaria

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', # 
]

# Media files (user uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # 

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URLs de redirección para autenticación
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'

JAZZMIN_SETTINGS = {
    # Títulos e Iconos
    "site_title": "Mi Admin",
    "site_header": "Mi Blog",
    "search_model": "auth.User",
    "site_brand": "Mi Blog",
    "welcome_sign": "Bienvenido a Mi Blog",
    "copyright": "Mi Blog Ltd.",

    # --- Menú Superior ---
    "topmenu_links": [
        # Ver Sitio
        {"name": "Ver Sitio", "url": "/", "new_window": False},

        # Enlace externo
        {"name": "Mi GitHub", "url": "https://github.com/EzequielEdOjeda/Blog_Django", "new_window": True},
    ],

    # --- Menú de Usuario ---
    "usermenu_links": [
        {"name": "Ver Sitio Web", "url": "/", "new_window": False},
    ],

    # --- Menú Lateral ---
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "posts", "accounts"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "posts.Post": "fas fa-blog",
        "posts.Comment": "fas fa-comments",
        "accounts.Profile": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # --- UI Customizer (Selector de Temas) ---
    "show_ui_builder": False, 
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
}

